#name: CI
#
on: [workflow_dispatch]
name: 🚀 Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    
    - name: Sync files
      uses: genietim/ftp-action@releases/v4.0.1
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        localDir: ""
        remoteDir: ""
